language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -e .  # needed to import itself
  - pip install pytest
  - pip install black
# command to run tests
script:
  - pytest
  - black --check periodic_table tests setup.py
